package main

var users []User = []User{
	{
		Name:   "Marilyn James",
		Age:    3043275287885634053,
		Active: false,
		HomeAddress: Address{
			Street: "Diane Coleman",
			City:   "Laura Campbell",
			State:  "Shirley Vasquez",
			Zip:    "Jesse Gardner",
		},
		FavoritePlaces: []Address{
			Address{
				Street: "Nancy Moreno",
				City:   "Wayne James",
				State:  "Marilyn Bishop",
				Zip:    "Doris Simpson",
			},
			Address{
				Street: "Pamela Turner",
				City:   "Ann Reed",
				State:  "Jesse Fowler",
				Zip:    "Gregory Lawson",
			},
			Address{
				Street: "Lois Anderson",
				City:   "Rachel Kim",
				State:  "Kathryn West",
				Zip:    "Scott Mason",
			},
			Address{
				Street: "Lawrence Clark",
				City:   "Jimmy Jones",
				State:  "Janet Graham",
				Zip:    "Catherine Hansen",
			},
		},
		Friends: []string{
			"Scott Welch",
			"Raymond Marshall",
			"Elizabeth Thompson",
			"Ruth Bryant",
			"Carl Mendoza",
			"Sarah Payne",
			"Billy Welch",
			"Donald Black",
			"Antonio Perkins",
			"William Reyes",
		},
	},
	{
		Name:   "Walter Jordan",
		Age:    7543050849516109910,
		Active: true,
		HomeAddress: Address{
			Street: "Gary Baker",
			City:   "Virginia Lawrence",
			State:  "Jessica Price",
			Zip:    "Lisa Meyer",
		},
		FavoritePlaces: []Address{
			Address{
				Street: "Keith Montgomery",
				City:   "Carol Hamilton",
				State:  "Lori Day",
				Zip:    "Christina Riley",
			},
			Address{
				Street: "Howard Fernandez",
				City:   "Gerald Peterson",
				State:  "Stephanie Bowman",
				Zip:    "Wayne Armstrong",
			},
			Address{
				Street: "Gloria Burke",
				City:   "Patrick Duncan",
				State:  "Antonio Matthews",
				Zip:    "Joyce Robertson",
			},
		},
		Friends: []string{
			"Ashley Young",
		},
	},
	{
		Name:   "Gerald Andrews",
		Age:    2071182381774700354,
		Active: true,
		HomeAddress: Address{
			Street: "Cynthia Alvarez",
			City:   "Walter Welch",
			State:  "Linda Jenkins",
			Zip:    "Russell Bryant",
		},
		FavoritePlaces: []Address{
			Address{
				Street: "Alice Allen",
				City:   "Todd Lopez",
				State:  "Norma Fowler",
				Zip:    "Phillip Welch",
			},
			Address{
				Street: "Julie Martin",
				City:   "Jeffrey Wood",
				State:  "Victor Anderson",
				Zip:    "Eric Mccoy",
			},
		},
		Friends: []string{
			"Ernest Woods",
			"Ruth Carpenter",
			"Elizabeth Clark",
			"Ruth Weaver",
			"Ralph Howell",
			"John Stevens",
			"Brenda Montgomery",
			"Kathryn Wilson",
		},
	},
	{
		Name:   "Henry Mendoza",
		Age:    4424189803603466885,
		Active: true,
		HomeAddress: Address{
			Street: "Anne Bradley",
			City:   "Ernest Martinez",
			State:  "Joshua Howard",
			Zip:    "Shawn Graham",
		},
		FavoritePlaces: []Address{
			Address{
				Street: "Nancy Dunn",
				City:   "Cynthia Gibson",
				State:  "Jean Cole",
				Zip:    "Maria Lawson",
			},
			Address{
				Street: "Steve Stanley",
				City:   "Steven Payne",
				State:  "Dennis Olson",
				Zip:    "Melissa Lee",
			},
			Address{
				Street: "Ashley Porter",
				City:   "Jessica Bennett",
				State:  "Michelle Johnston",
				Zip:    "Anthony Wood",
			},
		},
		Friends: []string{
			"Jeremy Black",
			"Stephen Morales",
		},
	},
	{
		Name:   "Paula Frazier",
		Age:    938219239573155046,
		Active: false,
		HomeAddress: Address{
			Street: "Theresa Bryant",
			City:   "Elizabeth Ross",
			State:  "Tammy Andrews",
			Zip:    "Anthony Gilbert",
		},
		FavoritePlaces: []Address{
			Address{
				Street: "Mark Rose",
				City:   "Benjamin Marshall",
				State:  "Christine Allen",
				Zip:    "William Phillips",
			},
		},
		Friends: []string{
			"Jason Fuller",
			"Lois Flores",
			"Marie Barnes",
			"Kathleen Mendoza",
			"Sean Riley",
			"Alice George",
			"Mildred Ray",
			"Elizabeth Sanchez",
			"Martin James",
		},
	},
	{
		Name:   "Joyce Dean",
		Age:    -6632101586460141321,
		Active: true,
		HomeAddress: Address{
			Street: "Michael Thompson",
			City:   "Christina Jordan",
			State:  "Wanda Kelly",
			Zip:    "Gregory Clark",
		},
		FavoritePlaces: []Address{
			Address{
				Street: "Robert Gonzales",
				City:   "Deborah Reyes",
				State:  "Russell Bowman",
				Zip:    "Patrick Ford",
			},
			Address{
				Street: "Patricia Mendoza",
				City:   "Roger Brown",
				State:  "Roger Coleman",
				Zip:    "Sarah Duncan",
			},
		},
		Friends: []string{
			"Judy Walker",
			"Pamela Scott",
			"Tammy Myers",
			"Dennis Sims",
			"Debra Clark",
			"Eric Collins",
			"Jonathan Smith",
			"Linda Bennett",
			"Paul Jones",
		},
	},
	{
		Name:   "Heather Rodriguez",
		Age:    4325819380196179196,
		Active: true,
		HomeAddress: Address{
			Street: "Barbara Ryan",
			City:   "Roy Hunt",
			State:  "Victor Wheeler",
			Zip:    "Paul Hansen",
		},
		FavoritePlaces: []Address{
			Address{
				Street: "Sara Wheeler",
				City:   "Samuel Hansen",
				State:  "Deborah Harrison",
				Zip:    "Kelly Holmes",
			},
			Address{
				Street: "Kevin Peters",
				City:   "Sara Gibson",
				State:  "Sharon Ellis",
				Zip:    "Jerry Ray",
			},
		},
		Friends: []string{
			"William Thomas",
			"Lawrence Thompson",
			"Timothy Ford",
			"Ruth Long",
			"Jerry Robinson",
			"Matthew Howell",
			"Amy Brooks",
			"Roy Wheeler",
			"Justin Hunt",
			"Wayne Sanders",
		},
	},
	{
		Name:   "Louis Hamilton",
		Age:    -7249063374932715361,
		Active: true,
		HomeAddress: Address{
			Street: "John Alexander",
			City:   "Douglas Robertson",
			State:  "Irene Ortiz",
			Zip:    "Russell Gibson",
		},
		FavoritePlaces: []Address{
			Address{
				Street: "Nicole Robinson",
				City:   "Peter Chavez",
				State:  "Carlos Wilson",
				Zip:    "Melissa Hawkins",
			},
		},
		Friends: []string{
			"Christopher Perkins",
			"Tammy Evans",
			"Mildred Perez",
			"Julia Hall",
			"Annie Foster",
			"Jimmy Wilson",
			"Marie Lynch",
			"Angela Hamilton",
			"Margaret Diaz",
		},
	},
	{
		Name:   "Louis Flores",
		Age:    -4009598923938205733,
		Active: false,
		HomeAddress: Address{
			Street: "Louis Watkins",
			City:   "Joshua Gonzales",
			State:  "Sean Boyd",
			Zip:    "Judith Bowman",
		},
		FavoritePlaces: []Address{
			Address{
				Street: "Katherine Rogers",
				City:   "Annie Montgomery",
				State:  "Antonio Porter",
				Zip:    "Ralph Henry",
			},
			Address{
				Street: "Judith Stephens",
				City:   "Benjamin Woods",
				State:  "Pamela Bell",
				Zip:    "Steven Mendoza",
			},
			Address{
				Street: "David Cruz",
				City:   "Ernest Payne",
				State:  "Paula Weaver",
				Zip:    "Christine Hill",
			},
			Address{
				Street: "James Gonzalez",
				City:   "Joshua Williamson",
				State:  "Billy Ryan",
				Zip:    "Jonathan Rodriguez",
			},
			Address{
				Street: "Christopher Hamilton",
				City:   "Aaron Arnold",
				State:  "Janice Diaz",
				Zip:    "Irene Rodriguez",
			},
		},
		Friends: []string{
			"Jessica Fields",
			"Christopher Hernandez",
			"Wayne Ferguson",
			"Brenda Gutierrez",
			"Jeffrey Boyd",
			"Alan Perkins",
			"Wayne Austin",
		},
	},
	{
		Name:   "Edward Bishop",
		Age:    5416584919038747639,
		Active: true,
		HomeAddress: Address{
			Street: "Heather Sullivan",
			City:   "Earl Watkins",
			State:  "Harold Kennedy",
			Zip:    "Julie Franklin",
		},
		FavoritePlaces: []Address{
			Address{
				Street: "Philip Hudson",
				City:   "Todd Mason",
				State:  "Peter Black",
				Zip:    "Janice Holmes",
			},
			Address{
				Street: "Paul Nichols",
				City:   "Howard Johnston",
				State:  "Sarah Fisher",
				Zip:    "Charles Meyer",
			},
			Address{
				Street: "Keith Garrett",
				City:   "Ronald Hernandez",
				State:  "Christine Carpenter",
				Zip:    "Robin Barnes",
			},
			Address{
				Street: "Lois Patterson",
				City:   "Justin Thomas",
				State:  "George Willis",
				Zip:    "Sara Pierce",
			},
		},
		Friends: []string{
			"Julie Long",
			"Timothy Watkins",
			"Ernest Roberts",
		},
	},
}
