package main

import (
	"github.com/gregpechiro/mockaroo/test-structs/address"
	"github.com/gregpechiro/mockaroo/test-structs/user"
)

var users []user.User = []user.User{
	{
		SomeMap: make(map[int]interface{}),
		Name:    "velit",
		Age:     -1927914292852161471,
		Active:  false,
		HomeAddress: address.Address{
			Street: "felis",
			City:   "leo",
			State:  "imperdiet sapien",
			Zip:    "rhoncus aliquet",
		},
		FavoritePlaces: []address.Address{
			address.Address{
				Street: "nam dui",
				City:   "vel nulla",
				State:  "ut ultrices",
				Zip:    "libero nam",
			},
			address.Address{
				Street: "justo sit",
				City:   "magnis",
				State:  "nisi vulputate",
				Zip:    "vivamus",
			},
			address.Address{
				Street: "vel",
				City:   "dui nec",
				State:  "pede ac",
				Zip:    "imperdiet sapien",
			},
		},
		Friends: []string{
			"lectus vestibulum",
			"lectus in",
		},
		Mother: "et tempus",
	},
	{
		SomeMap: make(map[int]interface{}),
		Name:    "quis",
		Age:     4609503208348241276,
		Active:  true,
		HomeAddress: address.Address{
			Street: "vel dapibus",
			City:   "sit",
			State:  "nulla justo",
			Zip:    "adipiscing lorem",
		},
		FavoritePlaces: []address.Address{
			address.Address{
				Street: "odio porttitor",
				City:   "congue vivamus",
				State:  "justo",
				Zip:    "ultrices phasellus",
			},
			address.Address{
				Street: "penatibus",
				City:   "ultrices",
				State:  "maecenas tincidunt",
				Zip:    "imperdiet nullam",
			},
			address.Address{
				Street: "consequat lectus",
				City:   "curae",
				State:  "nulla",
				Zip:    "id luctus",
			},
			address.Address{
				Street: "in",
				City:   "primis in",
				State:  "nulla facilisi",
				Zip:    "curae",
			},
			address.Address{
				Street: "amet",
				City:   "aliquet maecenas",
				State:  "eros vestibulum",
				Zip:    "aenean lectus",
			},
		},
		Friends: []string{
			"sapien a",
			"velit vivamus",
			"imperdiet",
			"imperdiet",
			"eget",
			"id sapien",
			"iaculis diam",
			"in",
			"dignissim",
			"commodo",
		},
		Mother: "suspendisse",
	},
	{
		SomeMap: make(map[int]interface{}),
		Name:    "morbi",
		Age:     -7063771959425447126,
		Active:  false,
		HomeAddress: address.Address{
			Street: "amet eros",
			City:   "nec sem",
			State:  "cras",
			Zip:    "duis consequat",
		},
		FavoritePlaces: []address.Address{
			address.Address{
				Street: "nulla pede",
				City:   "magna",
				State:  "pellentesque ultrices",
				Zip:    "ut rhoncus",
			},
			address.Address{
				Street: "curae",
				City:   "sit amet",
				State:  "habitasse platea",
				Zip:    "in felis",
			},
		},
		Friends: []string{
			"in",
			"sagittis dui",
			"ante vel",
			"bibendum",
			"leo",
			"pulvinar lobortis",
			"nonummy",
			"sapien dignissim",
			"tortor",
		},
		Mother: "curabitur in",
	},
	{
		SomeMap: make(map[int]interface{}),
		Name:    "luctus",
		Age:     -3567857724143231543,
		Active:  false,
		HomeAddress: address.Address{
			Street: "in",
			City:   "lacus morbi",
			State:  "erat eros",
			Zip:    "quam",
		},
		FavoritePlaces: []address.Address{
			address.Address{
				Street: "quis",
				City:   "morbi vestibulum",
				State:  "in hac",
				Zip:    "blandit nam",
			},
			address.Address{
				Street: "suscipit",
				City:   "varius nulla",
				State:  "quis",
				Zip:    "nulla",
			},
			address.Address{
				Street: "condimentum",
				City:   "blandit",
				State:  "augue vel",
				Zip:    "adipiscing elit",
			},
			address.Address{
				Street: "donec odio",
				City:   "justo sit",
				State:  "ultrices",
				Zip:    "rutrum",
			},
			address.Address{
				Street: "placerat",
				City:   "iaculis",
				State:  "at",
				Zip:    "convallis",
			},
		},
		Friends: []string{
			"nulla tempus",
			"porttitor lacus",
			"sapien sapien",
			"congue",
			"cras mi",
			"felis",
			"ut massa",
			"convallis nulla",
		},
		Mother: "lectus",
	},
	{
		SomeMap: make(map[int]interface{}),
		Name:    "at",
		Age:     5312195317278202694,
		Active:  true,
		HomeAddress: address.Address{
			Street: "at",
			City:   "nisi eu",
			State:  "vitae",
			Zip:    "dignissim vestibulum",
		},
		FavoritePlaces: []address.Address{
			address.Address{
				Street: "sem duis",
				City:   "lorem ipsum",
				State:  "quisque",
				Zip:    "magnis",
			},
		},
		Friends: []string{
			"nec",
			"ultrices",
			"orci",
			"maecenas leo",
		},
		Mother: "ligula",
	},
	{
		SomeMap: make(map[int]interface{}),
		Name:    "pharetra",
		Age:     -3584496058184363816,
		Active:  true,
		HomeAddress: address.Address{
			Street: "et magnis",
			City:   "vel nulla",
			State:  "felis sed",
			Zip:    "nulla",
		},
		FavoritePlaces: []address.Address{
			address.Address{
				Street: "justo",
				City:   "dictumst",
				State:  "dui",
				Zip:    "ante",
			},
			address.Address{
				Street: "sapien varius",
				City:   "nulla nunc",
				State:  "lorem",
				Zip:    "magna at",
			},
			address.Address{
				Street: "etiam",
				City:   "erat quisque",
				State:  "lobortis sapien",
				Zip:    "lobortis",
			},
			address.Address{
				Street: "ipsum dolor",
				City:   "sit",
				State:  "lorem",
				Zip:    "donec",
			},
			address.Address{
				Street: "integer aliquet",
				City:   "in",
				State:  "posuere felis",
				Zip:    "pellentesque ultrices",
			},
		},
		Friends: []string{
			"vestibulum ac",
			"sapien non",
			"nulla ac",
			"donec",
			"proin interdum",
			"ipsum aliquam",
			"id sapien",
			"interdum in",
			"turpis",
		},
		Mother: "libero",
	},
	{
		SomeMap: make(map[int]interface{}),
		Name:    "enim sit",
		Age:     -6448431640504719540,
		Active:  true,
		HomeAddress: address.Address{
			Street: "sit amet",
			City:   "turpis",
			State:  "vehicula condimentum",
			Zip:    "penatibus",
		},
		FavoritePlaces: []address.Address{
			address.Address{
				Street: "felis",
				City:   "nam",
				State:  "magna vulputate",
				Zip:    "sapien iaculis",
			},
			address.Address{
				Street: "donec",
				City:   "ligula",
				State:  "volutpat",
				Zip:    "mauris viverra",
			},
			address.Address{
				Street: "maecenas tincidunt",
				City:   "dui",
				State:  "vel pede",
				Zip:    "mauris enim",
			},
			address.Address{
				Street: "eros",
				City:   "lacus",
				State:  "volutpat eleifend",
				Zip:    "sem",
			},
			address.Address{
				Street: "sapien ut",
				City:   "ipsum ac",
				State:  "molestie",
				Zip:    "quisque",
			},
		},
		Friends: []string{
			"vivamus vestibulum",
			"quis",
		},
		Mother: "orci luctus",
	},
	{
		SomeMap: make(map[int]interface{}),
		Name:    "bibendum",
		Age:     -4197971978754026507,
		Active:  false,
		HomeAddress: address.Address{
			Street: "viverra pede",
			City:   "habitasse platea",
			State:  "odio cras",
			Zip:    "in lacus",
		},
		FavoritePlaces: []address.Address{
			address.Address{
				Street: "nec",
				City:   "justo morbi",
				State:  "eu sapien",
				Zip:    "felis",
			},
			address.Address{
				Street: "eu tincidunt",
				City:   "in",
				State:  "at nunc",
				Zip:    "congue etiam",
			},
			address.Address{
				Street: "proin",
				City:   "enim",
				State:  "augue",
				Zip:    "enim sit",
			},
			address.Address{
				Street: "vitae",
				City:   "adipiscing",
				State:  "tincidunt",
				Zip:    "dis",
			},
		},
		Friends: []string{
			"justo in",
			"eget",
			"iaculis justo",
			"morbi",
			"volutpat erat",
			"blandit lacinia",
			"tincidunt",
		},
		Mother: "dignissim vestibulum",
	},
	{
		SomeMap: make(map[int]interface{}),
		Name:    "in",
		Age:     -9213947914802260417,
		Active:  true,
		HomeAddress: address.Address{
			Street: "purus",
			City:   "sapien a",
			State:  "eu est",
			Zip:    "viverra",
		},
		FavoritePlaces: []address.Address{
			address.Address{
				Street: "mauris",
				City:   "curae",
				State:  "a",
				Zip:    "in",
			},
		},
		Friends: []string{
			"tortor",
			"varius",
			"pretium",
			"volutpat",
			"nec",
			"nibh",
		},
		Mother: "venenatis non",
	},
	{
		SomeMap: make(map[int]interface{}),
		Name:    "praesent",
		Age:     -2988703862838280781,
		Active:  false,
		HomeAddress: address.Address{
			Street: "morbi quis",
			City:   "dui vel",
			State:  "sed",
			Zip:    "praesent",
		},
		FavoritePlaces: []address.Address{
			address.Address{
				Street: "dolor quis",
				City:   "ante vel",
				State:  "diam erat",
				Zip:    "ultrices aliquet",
			},
		},
		Friends: []string{
			"quisque arcu",
			"ultrices aliquet",
			"id luctus",
			"egestas",
			"nullam sit",
			"elit sodales",
			"quis odio",
		},
		Mother: "id",
	},
}
